version: 0.2

env:
  variables:
      HOLA : 'Prueba'
      AWS_REGION : us-west-2

phases:
  install:
    runtime-versions:
        python: 3.7
  pre_build:
    commands:
      - apt-get update
      - echo $HOLA
      - echo $hija
      - echo $cedula
      - echo ---------------------------------------------------
      - aws --version
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - echo ---------------------------------------------------
  build:
    commands:
      - echo Empezando a construir `date`
      - export WORKSPACE=`pwd`
      - echo $WORKSPACE
  post_build:
    commands:
      - echo Construccion lista `date`
