version: 0.2

env:
  variables:
      BASE_URL : 'base_url=https://app.pandora.destacame.cl/external/api'
      RECAPTCHA_KEY : 'recaptcha_key=6Lcmc9IUAAAAAIkWWRIqvCFVPmwIU1FMgf8zsn0G'
      API_GATEWAY : 'API_GATEWAY= https://api.destacame.cl'
      AWS_BUCKET_NAME : 'AWS_BUCKET_NAME="nuxt.ares.destacame.cl"'
      AWS_CLOUDFRONT : 'AWS_CLOUDFRONT="UPPERCASE"'
      AWS_DEFAULT_REGION : 'AWS_DEFAULT_REGION="sa-east-1"'

phases:
  install:
    runtime-versions:
        python: 3.7
  pre_build:
    commands:
      # - apt-get update
      - echo $HOLA
      - echo $hija
      - echo $cedula
      - echo ---------------------------------------------------0
      - printf '%s\n' $BASE_URL $RECAPTCHA_KEY $API_GATEWAY $AWS_BUCKET_NAME $AWS_CLOUDFRONT $AWS_DEFAULT_REGION > aarnel_validation/andres.txt
      - echo ---------------------------------------------------
      - cat aarnel_validation/andres.txt
      - echo ---------------------------------------------------1
      - pwd
      - ls -l
      - echo ---------------------------------------------------2
      - ls -l aarnel_validation/
      - echo ---------------------------------------------------3
      - make all
      - aws --version
      - make -v
      # - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - echo ---------------------------------------------------4
  build:
    commands:
      - echo Empezando a construir `date`
      - export WORKSPACE=`pwd`
      - echo $WORKSPACE
  post_build:
    commands:
      - echo Construccion lista `date`
