version: 0.1

phases:
  pre_build:
    commands:
      - echo Instalo lo basico
      - sudo apt-get update
      - sudo pip install virtualenv
  build:
    commands:
      - echo Empezando a construir `date`
      - export WORKSPACE=`pwd`
      - echo $WORKSPACE    
  post_build:
    commands:
      - echo Construccion lista `date`
# artifacts:
#   files:
#     - core/target/scala-2.11/core_2.11-1.0.0.jar