version: 0.2

env:
  variables:
      HOLA : 'Prueba'

phases:
  install:
    runtime-versions:
        python: 3.7
  pre_build:
    commands:
      - echo ---------------------------------------------------
      - echo $HOLA
      - echo ---------------------------------------------------
      - echo $hija
      - echo $cedula
      - apt-get update
  build:
    commands:
      - echo Empezando a construir `date`
      - export WORKSPACE=`pwd`
      - echo $WORKSPACE
  post_build:
    commands:
      - echo Construccion lista `date`
