version: 0.2

env:
  variables:
      HOLA : 'Prueba'

phases:
  install:
    runtime-versions:
        python: 3.7
  pre_build:
    commands:
      - echo Esto es una prueba
      - sudo apt-get update
  build:
    commands:
      - echo Empezando a construir `date`
      - export WORKSPACE=`pwd`
      - echo $WORKSPACE
  post_build:
    commands:
      - echo Construccion lista `date`
